### ISSUE TITLE
How can i get A5 Paper?

### ISSUE THREAD

**Issue by MrJujuri** [OmiJod/Omi-printers#2]
How can i get A5 Paper? Please Help Me eheheh

**Comment by riedling11** [comment]
in the server.lua, its set to item "tosti" which is a grilled cheese sandwich.  you can use that for testing, but id change it to a different object.

**Comment by MrJujuri** [comment]
> in the server.lua, its set to item "tosti" which is a grilled cheese sandwich. you can use that for testing, but id change it to a different object.

Oh thank you for the answer its help me
